config/routes.rb
Rails.application.routes.draw do
  get 'home/bemvindo' => 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds

  root 'home#index'

end

app/models/kind.rb
class Kind < ActiveRecord::Base
    has_many :contacts, dependent: :nullify
    validates :description, presence: true, length: {minimum: 3}
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all.order(:description).page(params[:page]).per(15)
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_for(@kind, html: { class: "dark-matter" }) do |f| %>
  <% if @kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@kind.errors.count, 'error')} #{t('messages.errors')}:" %></h2>
      <ul>
      <% @kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <br><br>
    </div>
  <% end %>

  <h1>Cadastro de Tipos</h1>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-primary" %>
    <%= link_to 'Voltar', kinds_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<%= render 'form' %>

app/views/kinds/index.html.erb
<div class="dark-matter">
<script>
  $.notify("<%= notice %>", "success");
</script>
<h1><%= "#{t('headers.kind')} #{@kinds.model.model_name.human(count: @kinds.count)}" %></h1>
  
<table>
  <thead>
    <tr>
      <th><%= @kinds.model.human_attribute_name("description") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= link_to t('buttons.show'), kind, class: "btn btn-primary" %></td>
        <td><%= link_to t('buttons.edit'), edit_kind_path(kind), class: "btn btn-primary" %></td>
        <td><%= link_to t('buttons.destroy'), kind, method: :delete, data: { confirm: t('messages.destroy') }, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= paginate @kinds %>
<br>
<%= link_to t('buttons.new'), new_kind_path, class: "btn btn-primary" %>
<%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
</div>

app/views/kinds/new.html.erb
<%= render 'form' %>

app/views/kinds/show.html.erb
<div class="dark-matter">
<script>
  $.notify("<%= notice %>", "success");
</script>
<p>
  <strong><%= Kind.human_attribute_name("description") %>:</strong>
  <%= @kind.description %>
</p>

<%= link_to t('buttons.edit'), edit_kind_path(@kind), class: "btn btn-primary" %>
<%= link_to t('buttons.back'), kinds_path, class: "btn btn-primary" %>
</div>