config/routes.rb
Rails.application.routes.draw do
  get 'home/bemvindo' => 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds

  root 'home#index'

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]
  before_action :set_select_contact, only: [:new, :edit, :create, :update]

  # GET /phones
  # GET /phones.json
  def index
    respond_to do |format|
      format.html { @phones = Phone.all.order(:phone).page(params[:page]).per(15) }
    end
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    def set_select_contact
      @contact_options_select = Contact.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:phone, :contact_id)
    end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/index.html.erb
<div class="dark-matter">
<p id="notice"><%= notice %></p>

<h1><%= "#{t('headers.phone')} #{@phones.model.model_name.human(count: @phones.count)}" %></h1>


<table>
  <thead>
    <tr>
      <th><%= @phones.model.human_attribute_name("phone") %></th>
      <th><%= @phones.model.human_attribute_name("contact") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.phone %> </td>
        <td><%= phone.contact.name %></td>
        <td><%= link_to t('buttons.show'), phone, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= paginate @phones %>
<br>
<%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
</div>

app/views/phones/show.html.erb
<div class="dark-matter">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Phone.human_attribute_name("phone") %>:</strong>
  <%= @phone.phone %>
</p>

<p>
  <strong><%= Phone.human_attribute_name("contact") %>:</strong>
  <%= @phone.contact.name %>
</p>

<%= link_to t('buttons.back'), phones_path, class: "btn btn-primary" %>
</div>