config/routes.rb
Rails.application.routes.draw do
  get 'home/bemvindo' => 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds

  root 'home#index'

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :set_select_contact, only: [:new, :edit, :create, :update]


  # GET /addresses
  # GET /addresses.json
  def index
    respond_to do |format|
      format.html { @addresses = Address.all.order(:city).page(params[:page]).per(15) }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    def set_select_contact
      @contact_options_select = Contact.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :contact_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/index.html.erb
<div class="dark-matter">
<p id="notice"><%= notice %></p>

<h1><%= "#{t('headers.address')} #{@addresses.model.model_name.human(count: @addresses.count)}" %></h1>

<table>
  <thead>
    <tr>
      <th><%= @addresses.model.human_attribute_name("street") %></th>
      <th><%= @addresses.model.human_attribute_name("city") %></th>
      <th><%= @addresses.model.human_attribute_name("state") %></th>
      <th><%= @addresses.model.human_attribute_name("contact") %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.contact.try(:name) %></td>
        <td><%= link_to t('buttons.show'), address, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= paginate @addresses %>
<br>
<%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
</div>

app/views/addresses/show.html.erb
<div class="dark-matter">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Address.human_attribute_name("street") %>:</strong>
  <%= @address.street %>
</p>

<p>
  <strong><%= Address.human_attribute_name("city") %>:</strong>
  <%= @address.city %>
</p>

<p>
  <strong><%= Address.human_attribute_name("state") %>:</strong>
  <%= @address.state %>
</p>

<p>
  <strong><%= Address.human_attribute_name("contact") %>:</strong>
  <%= @address.contact.try(:name) %>
</p>

<%= link_to t('buttons.back'), addresses_path, class: "btn btn-primary" %>
</div>